export enum PitchType {
    AB = 'Automatic Ball',
    AS = 'Automatic Strike',
    CH = 'Change-up',
    CU = 'Curveball',
    CS = 'Slow Curve',
    EP = 'Eephus',
    FC = 'Cutter',
    FF = 'Four-Seam Fastball',
    FO = 'Forkball',
    FS = 'Splitter',
    FT = 'Two-Seam Fastball',
    GY = 'Gyroball',
    IN = 'Intentional Ball',
    KC = 'Knuckle Curve',
    KN = 'Knuckleball',
    NP = 'No Pitch',
    PO = 'Pitchout',
    SC = 'Screwball',
    SI = 'Sinker',
    SL = 'Slider',
    SV = 'Slurve',
    ST = 'Sweeper',
    UN = 'Unknown',
}
